log_level: debug

watcher:
  include:
    - views

builder:
  script: |
    npm run tailwind-rebuild
    go build -o ./ui github.com/i4n-co/driplimit/cmd/ui

runner:
  command: ./ui
  envs:
    - VIEWS_DIR=./views/
    - STATICS_DIR=./statics/
