# Config file for [Air](https://github.com/air-verse/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "tmp"

[build]
bin = "tmp/ui"
pre_cmd = ["killall ui || true && npm run tailwind-rebuild"]
cmd = "killall ui || true && go build -o tmp/ui github.com/i4n-co/driplimit/cmd/ui"
full_bin = "VIEWS_DIR=$(pwd)/views/ STATICS_DIR=$(pwd)/statics/ tmp/ui"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["node_modules"]
delay = 1000
stop_on_error = true
send_interrupt = false
kill_delay = 0 # nanosecond
rerun = true
rerun_delay = 100


[proxy]
  enabled = true
  proxy_port = 8090
  app_port = 8080

[log]
# Show log time
time = false
# Only show main log (silences watcher, build, runner)
main_only = false

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true

[screen]
clear_on_rebuild = false
keep_scroll = true